# Generated by Django 4.2.2 on 2023-06-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Ner_Api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gpe",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="loc",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="money",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="org",
            options={"managed": False},
        ),
    ]
