# Generated by Django 4.2.2 on 2023-06-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Ner_Api", "0002_alter_gpe_options_alter_loc_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gpe",
            table="gpe",
        ),
        migrations.AlterModelTable(
            name="loc",
            table="loc",
        ),
        migrations.AlterModelTable(
            name="money",
            table="money",
        ),
        migrations.AlterModelTable(
            name="org",
            table="org",
        ),
    ]
