# Generated by Django 4.2.2 on 2023-06-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ner_Api", "0003_alter_gpe_table_alter_loc_table_alter_money_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GpeEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gpe", models.CharField(max_length=100)),
                ("descript", models.TextField(max_length=1000)),
                ("summarized_description", models.TextField(max_length=1000)),
            ],
            options={
                "db_table": "gpe_entity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LocEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loc", models.CharField(max_length=250)),
                ("descript", models.TextField(max_length=1000)),
                ("summarized_description", models.TextField(max_length=1000)),
            ],
            options={
                "db_table": "loc_entity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MoneyEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.CharField(max_length=50)),
                ("descript", models.TextField(max_length=1000)),
                ("summarized_description", models.TextField(max_length=1000)),
            ],
            options={
                "db_table": "money_entity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrgEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org", models.CharField(max_length=100)),
                ("descript", models.TextField(max_length=1000)),
                ("summarized_description", models.TextField(max_length=1000)),
            ],
            options={
                "db_table": "org_entity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PersonEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.CharField(max_length=255)),
                ("descript", models.TextField(max_length=1000)),
                ("summarized_description", models.TextField(max_length=1000)),
            ],
            options={
                "db_table": "person_entity",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Gpe",
        ),
        migrations.DeleteModel(
            name="Loc",
        ),
        migrations.DeleteModel(
            name="Money",
        ),
        migrations.DeleteModel(
            name="Org",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
